import type { Instrument } from "../types";

/**
 * Seeded universe of large/mid-cap NSE names.
 *
 * IMPORTANT: every number below is *simulation input*, not real market data.
 * Prices, ratios and volumes are plausible ranges for each business so the
 * demo looks and behaves like the real thing, but they are not quotes and must
 * never be presented as such. Swap in a live provider for real values.
 */

/**
 * Shape of the last ~60 sessions of generated price action.
 *
 * The generator biases the random walk toward these regimes so that the
 * strategy engine — which runs genuine indicator maths on the output — has
 * real conditions to detect. Roughly a fifth of the universe is deliberately
 * `choppy` so that not every stock produces a signal.
 */
export type TechnicalScenario =
  | "ema-golden-cross"
  | "oversold-bounce"
  | "overbought-fade"
  | "range-breakout"
  | "support-bounce"
  | "macd-bull-cross"
  | "gap-up-continuation"
  | "gap-down-continuation"
  | "bb-squeeze-breakout"
  | "strong-uptrend"
  /** Wide-range session that opens near its low and closes near its high. */
  | "intraday-trend-day"
  | "downtrend"
  | "choppy";

/** Drives the fundamental figures used by the long-term strategies. */
export type FundamentalArchetype =
  | "deep-value"
  | "quality-growth"
  | "dividend-payer"
  | "high-growth"
  | "thematic-growth"
  | "cyclical"
  | "expensive-quality"
  | "leveraged";

export interface SeedInstrument extends Instrument {
  sim: {
    /** Approximate close ~14 months ago; the walk starts here. */
    basePrice: number;
    /** Annualised volatility, e.g. 0.28 = 28%. */
    annualVol: number;
    /** Annualised drift over the simulated window. */
    annualDrift: number;
    /** Typical daily traded quantity in shares. */
    avgVolume: number;
    scenario: TechnicalScenario;
    archetype: FundamentalArchetype;
    /** Explicit fundamental anchors; the rest is derived from the archetype. */
    pe: number;
    pb: number;
    roe: number;
    debtToEquity: number;
    dividendYield: number;
    themes: string[];
  };
}

/** Median P/E and P/B per sector, used for relative-value screening. */
export const SECTOR_STATS: Record<string, { pe: number; pb: number }> = {
  "Information Technology": { pe: 27.5, pb: 8.2 },
  "Financial Services": { pe: 17.8, pb: 2.6 },
  "Oil, Gas & Consumable Fuels": { pe: 14.2, pb: 1.9 },
  "Fast Moving Consumer Goods": { pe: 45.0, pb: 10.5 },
  Automobile: { pe: 24.0, pb: 4.1 },
  Healthcare: { pe: 31.0, pb: 4.6 },
  "Metals & Mining": { pe: 12.5, pb: 1.7 },
  Power: { pe: 16.0, pb: 2.2 },
  "Capital Goods": { pe: 38.0, pb: 6.4 },
  "Construction Materials": { pe: 35.0, pb: 4.2 },
  Telecommunication: { pe: 42.0, pb: 7.8 },
  "Consumer Durables": { pe: 52.0, pb: 12.0 },
  Services: { pe: 26.0, pb: 3.8 },
  "Capital Goods - Defence": { pe: 40.0, pb: 9.0 },
};

const N50 = "NIFTY 50";
const NEXT50 = "NIFTY NEXT 50";
const BANK = "NIFTY BANK";
const IT = "NIFTY IT";
const AUTO = "NIFTY AUTO";
const PHARMA = "NIFTY PHARMA";
const FMCG = "NIFTY FMCG";
const METAL = "NIFTY METAL";
const ENERGY = "NIFTY ENERGY";

export const SEED_INSTRUMENTS: SeedInstrument[] = [
  // ---------------------------------------------------------------- Energy
  {
    ticker: "RELIANCE",
    name: "Reliance Industries Ltd",
    exchange: "NSE",
    isin: "INE002A01018",
    sector: "Oil, Gas & Consumable Fuels",
    industry: "Refineries & Marketing",
    marketCapCr: 1_920_000,
    indices: [N50, ENERGY],
    providerToken: "2885",
    sim: {
      basePrice: 2480,
      annualVol: 0.24,
      annualDrift: 0.14,
      avgVolume: 8_400_000,
      scenario: "range-breakout",
      archetype: "quality-growth",
      pe: 24.8,
      pb: 2.1,
      roe: 9.2,
      debtToEquity: 0.44,
      dividendYield: 0.38,
      themes: ["Digital Infrastructure", "Renewable Energy", "Retail Consumption"],
    },
  },
  {
    ticker: "NTPC",
    name: "NTPC Ltd",
    exchange: "NSE",
    isin: "INE733E01010",
    sector: "Power",
    industry: "Power Generation",
    marketCapCr: 340_000,
    indices: [N50, ENERGY],
    providerToken: "11630",
    sim: {
      basePrice: 288,
      annualVol: 0.26,
      annualDrift: 0.22,
      avgVolume: 14_200_000,
      scenario: "strong-uptrend",
      archetype: "dividend-payer",
      pe: 15.4,
      pb: 2.0,
      roe: 13.8,
      debtToEquity: 1.42,
      dividendYield: 2.6,
      themes: ["Renewable Energy", "Power Capex Cycle"],
    },
  },
  {
    ticker: "POWERGRID",
    name: "Power Grid Corporation of India Ltd",
    exchange: "NSE",
    isin: "INE752E01010",
    sector: "Power",
    industry: "Power Transmission",
    marketCapCr: 280_000,
    indices: [N50, ENERGY],
    providerToken: "14977",
    sim: {
      basePrice: 258,
      annualVol: 0.22,
      annualDrift: 0.11,
      avgVolume: 11_800_000,
      scenario: "support-bounce",
      archetype: "dividend-payer",
      pe: 17.2,
      pb: 2.9,
      roe: 17.4,
      debtToEquity: 1.48,
      dividendYield: 3.4,
      themes: ["Power Capex Cycle", "Renewable Energy"],
    },
  },
  {
    ticker: "COALINDIA",
    name: "Coal India Ltd",
    exchange: "NSE",
    isin: "INE522F01014",
    sector: "Metals & Mining",
    industry: "Coal",
    marketCapCr: 240_000,
    indices: [N50, METAL],
    providerToken: "20374",
    sim: {
      basePrice: 402,
      annualVol: 0.30,
      annualDrift: -0.04,
      avgVolume: 12_600_000,
      scenario: "oversold-bounce",
      archetype: "deep-value",
      pe: 7.4,
      pb: 2.4,
      roe: 34.6,
      debtToEquity: 0.09,
      dividendYield: 6.2,
      themes: [],
    },
  },
  {
    ticker: "TATAPOWER",
    name: "Tata Power Company Ltd",
    exchange: "NSE",
    isin: "INE245A01021",
    sector: "Power",
    industry: "Integrated Power Utilities",
    marketCapCr: 128_000,
    indices: [NEXT50, ENERGY],
    providerToken: "3426",
    sim: {
      basePrice: 372,
      annualVol: 0.36,
      annualDrift: 0.18,
      avgVolume: 18_400_000,
      scenario: "bb-squeeze-breakout",
      archetype: "thematic-growth",
      pe: 34.2,
      pb: 3.6,
      roe: 11.2,
      debtToEquity: 1.12,
      dividendYield: 0.54,
      themes: ["Renewable Energy", "EV Charging Infrastructure", "Solar Manufacturing"],
    },
  },

  // ------------------------------------------------------------ Technology
  {
    ticker: "TCS",
    name: "Tata Consultancy Services Ltd",
    exchange: "NSE",
    isin: "INE467B01029",
    sector: "Information Technology",
    industry: "IT Services & Consulting",
    marketCapCr: 1_420_000,
    indices: [N50, IT],
    providerToken: "11536",
    sim: {
      basePrice: 3620,
      annualVol: 0.20,
      annualDrift: 0.08,
      avgVolume: 2_600_000,
      scenario: "choppy",
      archetype: "expensive-quality",
      pe: 28.6,
      pb: 14.2,
      roe: 51.4,
      debtToEquity: 0.09,
      dividendYield: 1.8,
      themes: ["AI Services", "Digital Infrastructure"],
    },
  },
  {
    ticker: "INFY",
    name: "Infosys Ltd",
    exchange: "NSE",
    isin: "INE009A01021",
    sector: "Information Technology",
    industry: "IT Services & Consulting",
    marketCapCr: 660_000,
    indices: [N50, IT],
    providerToken: "1594",
    sim: {
      basePrice: 1490,
      annualVol: 0.23,
      annualDrift: 0.12,
      avgVolume: 6_800_000,
      scenario: "ema-golden-cross",
      archetype: "quality-growth",
      pe: 24.9,
      pb: 8.1,
      roe: 31.8,
      debtToEquity: 0.09,
      dividendYield: 2.4,
      themes: ["AI Services", "Digital Infrastructure"],
    },
  },
  {
    ticker: "WIPRO",
    name: "Wipro Ltd",
    exchange: "NSE",
    isin: "INE075A01022",
    sector: "Information Technology",
    industry: "IT Services & Consulting",
    marketCapCr: 260_000,
    indices: [N50, IT],
    providerToken: "3787",
    sim: {
      basePrice: 262,
      annualVol: 0.25,
      annualDrift: -0.02,
      avgVolume: 9_200_000,
      scenario: "downtrend",
      archetype: "cyclical",
      pe: 21.4,
      pb: 3.4,
      roe: 15.2,
      debtToEquity: 0.24,
      dividendYield: 2.2,
      themes: ["AI Services"],
    },
  },
  {
    ticker: "HCLTECH",
    name: "HCL Technologies Ltd",
    exchange: "NSE",
    isin: "INE860A01027",
    sector: "Information Technology",
    industry: "IT Services & Consulting",
    marketCapCr: 460_000,
    indices: [N50, IT],
    providerToken: "7229",
    sim: {
      basePrice: 1420,
      annualVol: 0.22,
      annualDrift: 0.19,
      avgVolume: 3_400_000,
      scenario: "macd-bull-cross",
      archetype: "dividend-payer",
      pe: 25.8,
      pb: 6.2,
      roe: 24.6,
      debtToEquity: 0.08,
      dividendYield: 3.6,
      themes: ["AI Services", "Digital Infrastructure"],
    },
  },
  {
    ticker: "TECHM",
    name: "Tech Mahindra Ltd",
    exchange: "NSE",
    isin: "INE669C01036",
    sector: "Information Technology",
    industry: "IT Services & Consulting",
    marketCapCr: 152_000,
    indices: [N50, IT],
    providerToken: "13538",
    sim: {
      basePrice: 1280,
      annualVol: 0.28,
      annualDrift: 0.16,
      avgVolume: 4_100_000,
      scenario: "gap-up-continuation",
      archetype: "cyclical",
      pe: 36.2,
      pb: 4.8,
      roe: 13.4,
      debtToEquity: 0.12,
      dividendYield: 2.8,
      themes: ["AI Services", "5G Networks"],
    },
  },

  // ---------------------------------------------------- Financial Services
  {
    ticker: "HDFCBANK",
    name: "HDFC Bank Ltd",
    exchange: "NSE",
    isin: "INE040A01034",
    sector: "Financial Services",
    industry: "Private Sector Bank",
    marketCapCr: 1_280_000,
    indices: [N50, BANK],
    providerToken: "1333",
    sim: {
      basePrice: 1520,
      annualVol: 0.19,
      annualDrift: 0.13,
      avgVolume: 12_400_000,
      scenario: "ema-golden-cross",
      archetype: "quality-growth",
      pe: 18.4,
      pb: 2.7,
      roe: 16.8,
      debtToEquity: 0.0,
      dividendYield: 1.2,
      themes: ["Financial Inclusion", "Digital Infrastructure"],
    },
  },
  {
    ticker: "ICICIBANK",
    name: "ICICI Bank Ltd",
    exchange: "NSE",
    isin: "INE090A01021",
    sector: "Financial Services",
    industry: "Private Sector Bank",
    marketCapCr: 880_000,
    indices: [N50, BANK],
    providerToken: "4963",
    sim: {
      basePrice: 1050,
      annualVol: 0.20,
      annualDrift: 0.21,
      avgVolume: 10_800_000,
      scenario: "strong-uptrend",
      archetype: "quality-growth",
      pe: 18.9,
      pb: 3.2,
      roe: 18.4,
      debtToEquity: 0.0,
      dividendYield: 0.9,
      themes: ["Financial Inclusion", "Digital Infrastructure"],
    },
  },
  {
    ticker: "SBIN",
    name: "State Bank of India",
    exchange: "NSE",
    isin: "INE062A01020",
    sector: "Financial Services",
    industry: "Public Sector Bank",
    marketCapCr: 720_000,
    indices: [N50, BANK],
    providerToken: "3045",
    sim: {
      basePrice: 640,
      annualVol: 0.26,
      annualDrift: 0.17,
      avgVolume: 16_200_000,
      scenario: "range-breakout",
      archetype: "deep-value",
      pe: 10.2,
      pb: 1.7,
      roe: 17.9,
      debtToEquity: 0.0,
      dividendYield: 1.7,
      themes: ["Financial Inclusion", "Infrastructure Lending"],
    },
  },
  {
    ticker: "KOTAKBANK",
    name: "Kotak Mahindra Bank Ltd",
    exchange: "NSE",
    isin: "INE237A01028",
    sector: "Financial Services",
    industry: "Private Sector Bank",
    marketCapCr: 360_000,
    indices: [N50, BANK],
    providerToken: "1922",
    sim: {
      basePrice: 1780,
      annualVol: 0.22,
      annualDrift: 0.02,
      avgVolume: 5_600_000,
      scenario: "support-bounce",
      archetype: "quality-growth",
      pe: 17.6,
      pb: 2.6,
      roe: 15.4,
      debtToEquity: 0.0,
      dividendYield: 0.1,
      themes: ["Financial Inclusion"],
    },
  },
  {
    ticker: "AXISBANK",
    name: "Axis Bank Ltd",
    exchange: "NSE",
    isin: "INE238A01034",
    sector: "Financial Services",
    industry: "Private Sector Bank",
    marketCapCr: 340_000,
    indices: [N50, BANK],
    providerToken: "5900",
    sim: {
      basePrice: 1090,
      annualVol: 0.24,
      annualDrift: 0.06,
      avgVolume: 9_400_000,
      scenario: "oversold-bounce",
      archetype: "deep-value",
      pe: 13.1,
      pb: 2.1,
      roe: 16.2,
      debtToEquity: 0.0,
      dividendYield: 0.1,
      themes: ["Financial Inclusion"],
    },
  },
  {
    ticker: "BAJFINANCE",
    name: "Bajaj Finance Ltd",
    exchange: "NSE",
    isin: "INE296A01024",
    sector: "Financial Services",
    industry: "Non Banking Financial Company",
    marketCapCr: 440_000,
    indices: [N50],
    providerToken: "317",
    sim: {
      basePrice: 6800,
      annualVol: 0.29,
      annualDrift: 0.09,
      avgVolume: 1_900_000,
      scenario: "macd-bull-cross",
      archetype: "high-growth",
      pe: 29.4,
      pb: 5.6,
      roe: 20.8,
      debtToEquity: 3.62,
      dividendYield: 0.5,
      themes: ["Consumer Credit", "Digital Infrastructure"],
    },
  },

  // ------------------------------------------------------------------ FMCG
  {
    ticker: "HINDUNILVR",
    name: "Hindustan Unilever Ltd",
    exchange: "NSE",
    isin: "INE030A01027",
    sector: "Fast Moving Consumer Goods",
    industry: "Diversified FMCG",
    marketCapCr: 570_000,
    indices: [N50, FMCG],
    providerToken: "1394",
    sim: {
      basePrice: 2480,
      annualVol: 0.18,
      annualDrift: -0.03,
      avgVolume: 2_200_000,
      scenario: "downtrend",
      archetype: "expensive-quality",
      pe: 52.4,
      pb: 11.2,
      roe: 20.4,
      debtToEquity: 0.03,
      dividendYield: 1.7,
      themes: ["Rural Consumption"],
    },
  },
  {
    ticker: "ITC",
    name: "ITC Ltd",
    exchange: "NSE",
    isin: "INE154A01025",
    sector: "Fast Moving Consumer Goods",
    industry: "Diversified FMCG",
    marketCapCr: 560_000,
    indices: [N50, FMCG],
    providerToken: "1660",
    sim: {
      basePrice: 442,
      annualVol: 0.19,
      annualDrift: 0.07,
      avgVolume: 15_800_000,
      scenario: "support-bounce",
      archetype: "dividend-payer",
      pe: 26.1,
      pb: 7.4,
      roe: 28.6,
      debtToEquity: 0.0,
      dividendYield: 3.4,
      themes: ["Rural Consumption", "Hotels & Travel"],
    },
  },
  {
    ticker: "NESTLEIND",
    name: "Nestle India Ltd",
    exchange: "NSE",
    isin: "INE239A01024",
    sector: "Fast Moving Consumer Goods",
    industry: "Packaged Foods",
    marketCapCr: 218_000,
    indices: [N50, FMCG],
    providerToken: "17963",
    sim: {
      basePrice: 2320,
      annualVol: 0.17,
      annualDrift: 0.01,
      avgVolume: 1_400_000,
      scenario: "choppy",
      archetype: "expensive-quality",
      pe: 68.2,
      pb: 58.4,
      roe: 92.6,
      debtToEquity: 0.04,
      dividendYield: 1.1,
      themes: ["Rural Consumption"],
    },
  },
  {
    ticker: "DABUR",
    name: "Dabur India Ltd",
    exchange: "NSE",
    isin: "INE016A01026",
    sector: "Fast Moving Consumer Goods",
    industry: "Personal Care",
    marketCapCr: 92_000,
    indices: [NEXT50, FMCG],
    providerToken: "772",
    sim: {
      basePrice: 528,
      annualVol: 0.21,
      annualDrift: -0.06,
      avgVolume: 2_800_000,
      scenario: "oversold-bounce",
      archetype: "dividend-payer",
      pe: 44.8,
      pb: 8.6,
      roe: 19.2,
      debtToEquity: 0.11,
      dividendYield: 1.4,
      themes: ["Rural Consumption", "Ayurveda & Wellness"],
    },
  },

  // ------------------------------------------------------------ Automobile
  {
    ticker: "MARUTI",
    name: "Maruti Suzuki India Ltd",
    exchange: "NSE",
    isin: "INE585B01010",
    sector: "Automobile",
    industry: "Passenger Cars & Utility Vehicles",
    marketCapCr: 390_000,
    indices: [N50, AUTO],
    providerToken: "10999",
    sim: {
      basePrice: 11_200,
      annualVol: 0.24,
      annualDrift: 0.15,
      avgVolume: 700_000,
      scenario: "range-breakout",
      archetype: "quality-growth",
      pe: 26.4,
      pb: 4.2,
      roe: 16.8,
      debtToEquity: 0.01,
      dividendYield: 1.1,
      themes: ["Premiumisation", "Hybrid & EV Transition"],
    },
  },
  {
    ticker: "TATAMOTORS",
    name: "Tata Motors Ltd",
    exchange: "NSE",
    isin: "INE155A01022",
    sector: "Automobile",
    industry: "Commercial Vehicles",
    marketCapCr: 280_000,
    indices: [N50, AUTO],
    providerToken: "3456",
    sim: {
      basePrice: 940,
      annualVol: 0.34,
      annualDrift: -0.12,
      avgVolume: 13_600_000,
      scenario: "gap-down-continuation",
      archetype: "cyclical",
      pe: 9.8,
      pb: 2.9,
      roe: 32.4,
      debtToEquity: 0.86,
      dividendYield: 0.7,
      themes: ["Hybrid & EV Transition", "EV Charging Infrastructure"],
    },
  },
  {
    ticker: "M&M",
    name: "Mahindra & Mahindra Ltd",
    exchange: "NSE",
    isin: "INE101A01026",
    sector: "Automobile",
    industry: "Passenger Cars & Utility Vehicles",
    marketCapCr: 370_000,
    indices: [N50, AUTO],
    providerToken: "2031",
    sim: {
      basePrice: 2620,
      annualVol: 0.27,
      annualDrift: 0.28,
      avgVolume: 3_200_000,
      scenario: "strong-uptrend",
      archetype: "high-growth",
      pe: 29.8,
      pb: 5.1,
      roe: 18.6,
      debtToEquity: 0.32,
      dividendYield: 0.7,
      themes: ["Hybrid & EV Transition", "Rural Consumption", "Premiumisation"],
    },
  },
  {
    ticker: "EICHERMOT",
    name: "Eicher Motors Ltd",
    exchange: "NSE",
    isin: "INE066A01021",
    sector: "Automobile",
    industry: "2/3 Wheelers",
    marketCapCr: 132_000,
    indices: [N50, AUTO],
    providerToken: "910",
    sim: {
      basePrice: 4180,
      annualVol: 0.26,
      annualDrift: 0.20,
      avgVolume: 1_100_000,
      scenario: "bb-squeeze-breakout",
      archetype: "quality-growth",
      pe: 31.2,
      pb: 6.8,
      roe: 22.4,
      debtToEquity: 0.02,
      dividendYield: 1.3,
      themes: ["Premiumisation"],
    },
  },

  // -------------------------------------------------------------- Pharma
  {
    ticker: "SUNPHARMA",
    name: "Sun Pharmaceutical Industries Ltd",
    exchange: "NSE",
    isin: "INE044A01036",
    sector: "Healthcare",
    industry: "Pharmaceuticals",
    marketCapCr: 420_000,
    indices: [N50, PHARMA],
    providerToken: "3351",
    sim: {
      basePrice: 1480,
      annualVol: 0.23,
      annualDrift: 0.24,
      avgVolume: 2_900_000,
      scenario: "strong-uptrend",
      archetype: "quality-growth",
      pe: 34.6,
      pb: 5.8,
      roe: 17.2,
      debtToEquity: 0.04,
      dividendYield: 0.9,
      themes: ["Specialty Pharma", "Healthcare Access"],
    },
  },
  {
    ticker: "DRREDDY",
    name: "Dr. Reddy's Laboratories Ltd",
    exchange: "NSE",
    isin: "INE089A01031",
    sector: "Healthcare",
    industry: "Pharmaceuticals",
    marketCapCr: 106_000,
    indices: [N50, PHARMA],
    providerToken: "881",
    sim: {
      basePrice: 1280,
      annualVol: 0.25,
      annualDrift: -0.08,
      avgVolume: 2_400_000,
      scenario: "overbought-fade",
      archetype: "deep-value",
      pe: 18.2,
      pb: 3.2,
      roe: 19.4,
      debtToEquity: 0.08,
      dividendYield: 0.7,
      themes: ["Specialty Pharma", "Healthcare Access"],
    },
  },
  {
    ticker: "CIPLA",
    name: "Cipla Ltd",
    exchange: "NSE",
    isin: "INE059A01026",
    sector: "Healthcare",
    industry: "Pharmaceuticals",
    marketCapCr: 122_000,
    indices: [N50, PHARMA],
    providerToken: "694",
    sim: {
      basePrice: 1420,
      annualVol: 0.22,
      annualDrift: 0.10,
      avgVolume: 2_100_000,
      scenario: "macd-bull-cross",
      archetype: "quality-growth",
      pe: 24.8,
      pb: 3.9,
      roe: 16.4,
      debtToEquity: 0.03,
      dividendYield: 0.9,
      themes: ["Healthcare Access", "Specialty Pharma"],
    },
  },

  // ------------------------------------------------------------- Metals
  {
    ticker: "TATASTEEL",
    name: "Tata Steel Ltd",
    exchange: "NSE",
    isin: "INE081A01020",
    sector: "Metals & Mining",
    industry: "Iron & Steel",
    marketCapCr: 190_000,
    indices: [N50, METAL],
    providerToken: "3499",
    sim: {
      basePrice: 142,
      annualVol: 0.33,
      annualDrift: 0.06,
      avgVolume: 42_000_000,
      scenario: "intraday-trend-day",
      archetype: "cyclical",
      pe: 42.6,
      pb: 2.2,
      roe: 5.4,
      debtToEquity: 1.18,
      dividendYield: 2.4,
      themes: ["Infrastructure Capex"],
    },
  },
  {
    ticker: "JSWSTEEL",
    name: "JSW Steel Ltd",
    exchange: "NSE",
    isin: "INE019A01038",
    sector: "Metals & Mining",
    industry: "Iron & Steel",
    marketCapCr: 240_000,
    indices: [N50, METAL],
    providerToken: "11723",
    sim: {
      basePrice: 880,
      annualVol: 0.30,
      annualDrift: 0.12,
      avgVolume: 6_400_000,
      scenario: "intraday-trend-day",
      archetype: "leveraged",
      pe: 38.4,
      pb: 3.1,
      roe: 8.2,
      debtToEquity: 1.34,
      dividendYield: 0.8,
      themes: ["Infrastructure Capex"],
    },
  },

  // --------------------------------------------- Capital goods / Infra
  {
    ticker: "LT",
    name: "Larsen & Toubro Ltd",
    exchange: "NSE",
    isin: "INE018A01030",
    sector: "Capital Goods",
    industry: "Civil Construction",
    marketCapCr: 500_000,
    indices: [N50],
    providerToken: "11483",
    sim: {
      basePrice: 3320,
      annualVol: 0.25,
      annualDrift: 0.18,
      avgVolume: 3_100_000,
      scenario: "ema-golden-cross",
      archetype: "thematic-growth",
      pe: 34.2,
      pb: 5.4,
      roe: 15.8,
      debtToEquity: 0.58,
      dividendYield: 0.8,
      themes: ["Infrastructure Capex", "Defence Manufacturing", "Renewable Energy"],
    },
  },
  {
    ticker: "ULTRACEMCO",
    name: "UltraTech Cement Ltd",
    exchange: "NSE",
    isin: "INE481G01011",
    sector: "Construction Materials",
    industry: "Cement & Cement Products",
    marketCapCr: 320_000,
    indices: [N50],
    providerToken: "11532",
    sim: {
      basePrice: 10_400,
      annualVol: 0.23,
      annualDrift: 0.11,
      avgVolume: 620_000,
      scenario: "intraday-trend-day",
      archetype: "quality-growth",
      pe: 44.6,
      pb: 4.8,
      roe: 11.2,
      debtToEquity: 0.21,
      dividendYield: 0.7,
      themes: ["Infrastructure Capex", "Housing Demand"],
    },
  },
  {
    ticker: "ADANIPORTS",
    name: "Adani Ports and Special Economic Zone Ltd",
    exchange: "NSE",
    isin: "INE742F01042",
    sector: "Services",
    industry: "Port & Port Services",
    marketCapCr: 290_000,
    indices: [N50],
    providerToken: "15083",
    sim: {
      basePrice: 1240,
      annualVol: 0.32,
      annualDrift: 0.14,
      avgVolume: 5_800_000,
      scenario: "gap-up-continuation",
      archetype: "thematic-growth",
      pe: 27.8,
      pb: 4.4,
      roe: 17.6,
      debtToEquity: 0.78,
      dividendYield: 0.5,
      themes: ["Infrastructure Capex", "Logistics & Supply Chain"],
    },
  },

  // ---------------------------------------------------------- Consumer
  {
    ticker: "ASIANPAINT",
    name: "Asian Paints Ltd",
    exchange: "NSE",
    isin: "INE021A01026",
    sector: "Consumer Durables",
    industry: "Paints",
    marketCapCr: 232_000,
    indices: [N50],
    providerToken: "236",
    sim: {
      basePrice: 2860,
      annualVol: 0.24,
      annualDrift: -0.18,
      avgVolume: 2_600_000,
      scenario: "downtrend",
      archetype: "expensive-quality",
      pe: 48.2,
      pb: 12.4,
      roe: 26.4,
      debtToEquity: 0.06,
      dividendYield: 1.3,
      themes: ["Housing Demand", "Premiumisation"],
    },
  },
  {
    ticker: "TITAN",
    name: "Titan Company Ltd",
    exchange: "NSE",
    isin: "INE280A01028",
    sector: "Consumer Durables",
    industry: "Gems, Jewellery & Watches",
    marketCapCr: 300_000,
    indices: [N50],
    providerToken: "3506",
    sim: {
      basePrice: 3280,
      annualVol: 0.26,
      annualDrift: 0.09,
      avgVolume: 1_700_000,
      scenario: "overbought-fade",
      archetype: "high-growth",
      pe: 88.4,
      pb: 26.2,
      roe: 32.8,
      debtToEquity: 0.72,
      dividendYield: 0.3,
      themes: ["Premiumisation", "Organised Retail"],
    },
  },

  // ----------------------------------------------------------- Defence
  {
    ticker: "HAL",
    name: "Hindustan Aeronautics Ltd",
    exchange: "NSE",
    isin: "INE066F01020",
    sector: "Capital Goods - Defence",
    industry: "Aerospace & Defence",
    marketCapCr: 300_000,
    indices: [N50],
    providerToken: "2303",
    sim: {
      basePrice: 4100,
      annualVol: 0.38,
      annualDrift: 0.26,
      avgVolume: 2_400_000,
      scenario: "bb-squeeze-breakout",
      archetype: "thematic-growth",
      pe: 33.6,
      pb: 8.2,
      roe: 27.4,
      debtToEquity: 0.0,
      dividendYield: 0.9,
      themes: ["Defence Manufacturing", "PLI Beneficiary", "Make in India"],
    },
  },
  {
    ticker: "BEL",
    name: "Bharat Electronics Ltd",
    exchange: "NSE",
    isin: "INE263A01024",
    sector: "Capital Goods - Defence",
    industry: "Aerospace & Defence",
    marketCapCr: 240_000,
    indices: [N50],
    providerToken: "383",
    sim: {
      basePrice: 268,
      annualVol: 0.36,
      annualDrift: 0.34,
      avgVolume: 22_000_000,
      scenario: "strong-uptrend",
      archetype: "thematic-growth",
      pe: 44.2,
      pb: 12.6,
      roe: 29.8,
      debtToEquity: 0.0,
      dividendYield: 0.8,
      themes: ["Defence Manufacturing", "PLI Beneficiary", "Make in India", "Semiconductors"],
    },
  },

  // --------------------------------------------------------- Telecom
  {
    ticker: "BHARTIARTL",
    name: "Bharti Airtel Ltd",
    exchange: "NSE",
    isin: "INE397D01024",
    sector: "Telecommunication",
    industry: "Telecom Services",
    marketCapCr: 980_000,
    indices: [N50],
    providerToken: "10604",
    sim: {
      basePrice: 1420,
      annualVol: 0.24,
      annualDrift: 0.29,
      avgVolume: 8_200_000,
      scenario: "range-breakout",
      archetype: "thematic-growth",
      pe: 46.8,
      pb: 9.4,
      roe: 21.2,
      debtToEquity: 1.24,
      dividendYield: 0.6,
      themes: ["5G Networks", "Digital Infrastructure", "Data Centres"],
    },
  },

  // ----------------------------------------- Consumer Tech & New-Age Growth
  {
    ticker: "ZOMATO",
    name: "Zomato Ltd",
    exchange: "NSE",
    isin: "INE758T01015",
    sector: "Services",
    industry: "E-Commerce / Food Delivery",
    marketCapCr: 240_000,
    indices: [NEXT50],
    providerToken: "5097",
    sim: {
      basePrice: 260,
      annualVol: 0.42,
      annualDrift: 0.38,
      avgVolume: 45_000_000,
      scenario: "strong-uptrend",
      archetype: "high-growth",
      pe: 95.0,
      pb: 11.2,
      roe: 8.4,
      debtToEquity: 0.0,
      dividendYield: 0.0,
      themes: ["Digital Infrastructure", "Quick Commerce", "Retail Consumption"],
    },
  },
  {
    ticker: "PAYTM",
    name: "One97 Communications Ltd",
    exchange: "NSE",
    isin: "INE982J01020",
    sector: "Financial Services",
    industry: "Financial Technology",
    marketCapCr: 48_000,
    indices: [],
    providerToken: "5109",
    sim: {
      basePrice: 740,
      annualVol: 0.48,
      annualDrift: 0.14,
      avgVolume: 12_000_000,
      scenario: "oversold-bounce",
      archetype: "high-growth",
      pe: 42.0,
      pb: 3.4,
      roe: 4.2,
      debtToEquity: 0.02,
      dividendYield: 0.0,
      themes: ["Digital Infrastructure", "Financial Inclusion"],
    },
  },
  {
    ticker: "JIOFIN",
    name: "Jio Financial Services Ltd",
    exchange: "NSE",
    isin: "INE758E01017",
    sector: "Financial Services",
    industry: "Non Banking Financial Company",
    marketCapCr: 210_000,
    indices: [NEXT50],
    providerToken: "20870",
    sim: {
      basePrice: 330,
      annualVol: 0.35,
      annualDrift: 0.22,
      avgVolume: 18_000_000,
      scenario: "range-breakout",
      archetype: "thematic-growth",
      pe: 110.0,
      pb: 1.6,
      roe: 2.1,
      debtToEquity: 0.01,
      dividendYield: 0.0,
      themes: ["Financial Inclusion", "Digital Infrastructure", "Consumer Credit"],
    },
  },

  // --------------------------------------------- Railway, PSU & Defence
  {
    ticker: "IRFC",
    name: "Indian Railway Finance Corporation Ltd",
    exchange: "NSE",
    isin: "INE053F01010",
    sector: "Financial Services",
    industry: "Rail Finance PSU",
    marketCapCr: 210_000,
    indices: [NEXT50],
    providerToken: "3263",
    sim: {
      basePrice: 160,
      annualVol: 0.45,
      annualDrift: 0.32,
      avgVolume: 35_000_000,
      scenario: "strong-uptrend",
      archetype: "dividend-payer",
      pe: 31.0,
      pb: 4.2,
      roe: 13.8,
      debtToEquity: 8.4,
      dividendYield: 1.2,
      themes: ["Infrastructure Capex", "Railway Capex", "PSU Modernisation"],
    },
  },
  {
    ticker: "RVNL",
    name: "Rail Vikas Nigam Ltd",
    exchange: "NSE",
    isin: "INE415G01027",
    sector: "Capital Goods",
    industry: "Railway Infrastructure Construction",
    marketCapCr: 110_000,
    indices: [],
    providerToken: "19313",
    sim: {
      basePrice: 520,
      annualVol: 0.52,
      annualDrift: 0.41,
      avgVolume: 28_000_000,
      scenario: "bb-squeeze-breakout",
      archetype: "thematic-growth",
      pe: 64.0,
      pb: 12.8,
      roe: 21.4,
      debtToEquity: 0.85,
      dividendYield: 0.4,
      themes: ["Infrastructure Capex", "Railway Capex", "Make in India"],
    },
  },
  {
    ticker: "MAZDOCK",
    name: "Mazagon Dock Shipbuilders Ltd",
    exchange: "NSE",
    isin: "INE249Z01012",
    sector: "Capital Goods - Defence",
    industry: "Shipbuilding & Submarines",
    marketCapCr: 92_000,
    indices: [],
    providerToken: "467",
    sim: {
      basePrice: 4400,
      annualVol: 0.55,
      annualDrift: 0.48,
      avgVolume: 8_500_000,
      scenario: "strong-uptrend",
      archetype: "thematic-growth",
      pe: 42.0,
      pb: 11.5,
      roe: 38.0,
      debtToEquity: 0.0,
      dividendYield: 0.6,
      themes: ["Defence Manufacturing", "Make in India", "PLI Beneficiary"],
    },
  },
  {
    ticker: "BHEL",
    name: "Bharat Heavy Electricals Ltd",
    exchange: "NSE",
    isin: "INE257A01026",
    sector: "Capital Goods",
    industry: "Heavy Electrical Equipment",
    marketCapCr: 98_000,
    indices: [NEXT50],
    providerToken: "438",
    sim: {
      basePrice: 290,
      annualVol: 0.40,
      annualDrift: 0.28,
      avgVolume: 24_000_000,
      scenario: "gap-up-continuation",
      archetype: "cyclical",
      pe: 180.0,
      pb: 3.8,
      roe: 1.8,
      debtToEquity: 0.28,
      dividendYield: 0.1,
      themes: ["Power Capex Cycle", "Infrastructure Capex"],
    },
  },
  {
    ticker: "RECLTD",
    name: "REC Ltd",
    exchange: "NSE",
    isin: "INE020B01018",
    sector: "Financial Services",
    industry: "Power Finance PSU",
    marketCapCr: 155_000,
    indices: [NEXT50],
    providerToken: "15355",
    sim: {
      basePrice: 580,
      annualVol: 0.38,
      annualDrift: 0.35,
      avgVolume: 16_000_000,
      scenario: "macd-bull-cross",
      archetype: "dividend-payer",
      pe: 10.8,
      pb: 2.2,
      roe: 21.5,
      debtToEquity: 6.8,
      dividendYield: 2.8,
      themes: ["Power Capex Cycle", "Renewable Energy"],
    },
  },
  {
    ticker: "PFC",
    name: "Power Finance Corporation Ltd",
    exchange: "NSE",
    isin: "INE134E01011",
    sector: "Financial Services",
    industry: "Power Finance PSU",
    marketCapCr: 165_000,
    indices: [NEXT50],
    providerToken: "14299",
    sim: {
      basePrice: 500,
      annualVol: 0.36,
      annualDrift: 0.32,
      avgVolume: 18_000_000,
      scenario: "ema-golden-cross",
      archetype: "dividend-payer",
      pe: 9.6,
      pb: 2.0,
      roe: 22.1,
      debtToEquity: 6.2,
      dividendYield: 2.7,
      themes: ["Power Capex Cycle", "Renewable Energy"],
    },
  },

  // --------------------------------------- Retail, Chemicals & Consumer
  {
    ticker: "TRENT",
    name: "Trent Ltd",
    exchange: "NSE",
    isin: "INE849A01020",
    sector: "Consumer Durables",
    industry: "Apparel Retail (Westside & Zudio)",
    marketCapCr: 250_000,
    indices: [N50],
    providerToken: "1964",
    sim: {
      basePrice: 7100,
      annualVol: 0.38,
      annualDrift: 0.52,
      avgVolume: 2_800_000,
      scenario: "strong-uptrend",
      archetype: "high-growth",
      pe: 155.0,
      pb: 48.0,
      roe: 35.0,
      debtToEquity: 0.42,
      dividendYield: 0.1,
      themes: ["Organised Retail", "Premiumisation", "Retail Consumption"],
    },
  },
  {
    ticker: "DMART",
    name: "Avenue Supermarts Ltd",
    exchange: "NSE",
    isin: "INE192R01011",
    sector: "Fast Moving Consumer Goods",
    industry: "Hypermarkets & Supermarkets",
    marketCapCr: 310_000,
    indices: [NEXT50],
    providerToken: "19723",
    sim: {
      basePrice: 4800,
      annualVol: 0.26,
      annualDrift: 0.15,
      avgVolume: 1_200_000,
      scenario: "range-breakout",
      archetype: "expensive-quality",
      pe: 118.0,
      pb: 16.5,
      roe: 15.2,
      debtToEquity: 0.04,
      dividendYield: 0.0,
      themes: ["Organised Retail", "Retail Consumption"],
    },
  },
  {
    ticker: "DLF",
    name: "DLF Ltd",
    exchange: "NSE",
    isin: "INE271C01023",
    sector: "Services",
    industry: "Real Estate Development",
    marketCapCr: 215_000,
    indices: [NEXT50],
    providerToken: "14732",
    sim: {
      basePrice: 860,
      annualVol: 0.34,
      annualDrift: 0.28,
      avgVolume: 6_200_000,
      scenario: "ema-golden-cross",
      archetype: "thematic-growth",
      pe: 78.0,
      pb: 5.6,
      roe: 7.2,
      debtToEquity: 0.06,
      dividendYield: 0.5,
      themes: ["Housing Demand", "Premiumisation"],
    },
  },
  {
    ticker: "SUZLON",
    name: "Suzlon Energy Ltd",
    exchange: "NSE",
    isin: "INE040H01021",
    sector: "Power",
    industry: "Wind Turbine Manufacturing",
    marketCapCr: 95_000,
    indices: [],
    providerToken: "13396",
    sim: {
      basePrice: 72,
      annualVol: 0.62,
      annualDrift: 0.58,
      avgVolume: 85_000_000,
      scenario: "strong-uptrend",
      archetype: "thematic-growth",
      pe: 92.0,
      pb: 22.0,
      roe: 28.0,
      debtToEquity: 0.0,
      dividendYield: 0.0,
      themes: ["Renewable Energy", "Power Capex Cycle", "PLI Beneficiary"],
    },
  },
  {
    ticker: "VBL",
    name: "Varun Beverages Ltd",
    exchange: "NSE",
    isin: "INE200M01021",
    sector: "Fast Moving Consumer Goods",
    industry: "Beverages (Pepsi Bottler)",
    marketCapCr: 210_000,
    indices: [NEXT50],
    providerToken: "19585",
    sim: {
      basePrice: 620,
      annualVol: 0.28,
      annualDrift: 0.36,
      avgVolume: 9_200_000,
      scenario: "macd-bull-cross",
      archetype: "high-growth",
      pe: 82.0,
      pb: 24.0,
      roe: 31.0,
      debtToEquity: 0.72,
      dividendYield: 0.2,
      themes: ["Retail Consumption", "Rural Consumption"],
    },
  },
  {
    ticker: "POLYCAB",
    name: "Polycab India Ltd",
    exchange: "NSE",
    isin: "INE455K01017",
    sector: "Capital Goods",
    industry: "Wires & Cables",
    marketCapCr: 98_000,
    indices: [NEXT50],
    providerToken: "1954",
    sim: {
      basePrice: 6500,
      annualVol: 0.32,
      annualDrift: 0.26,
      avgVolume: 1_100_000,
      scenario: "range-breakout",
      archetype: "quality-growth",
      pe: 52.0,
      pb: 12.0,
      roe: 24.5,
      debtToEquity: 0.02,
      dividendYield: 0.5,
      themes: ["Infrastructure Capex", "Housing Demand"],
    },
  },
  {
    ticker: "BAJAJ-AUTO",
    name: "Bajaj Auto Ltd",
    exchange: "NSE",
    isin: "INE917I01010",
    sector: "Automobile",
    industry: "2/3 Wheelers & Commercial EVs",
    marketCapCr: 270_000,
    indices: [N50, AUTO],
    providerToken: "16669",
    sim: {
      basePrice: 9600,
      annualVol: 0.27,
      annualDrift: 0.38,
      avgVolume: 850_000,
      scenario: "strong-uptrend",
      archetype: "quality-growth",
      pe: 34.0,
      pb: 9.5,
      roe: 28.5,
      debtToEquity: 0.0,
      dividendYield: 1.4,
      themes: ["Hybrid & EV Transition", "Premiumisation"],
    },
  },
  {
    ticker: "VEDL",
    name: "Vedanta Ltd",
    exchange: "NSE",
    isin: "INE205A01025",
    sector: "Metals & Mining",
    industry: "Diversified Mining & Metals",
    marketCapCr: 175_000,
    indices: [NEXT50, METAL],
    providerToken: "3067",
    sim: {
      basePrice: 460,
      annualVol: 0.42,
      annualDrift: 0.25,
      avgVolume: 24_000_000,
      scenario: "oversold-bounce",
      archetype: "dividend-payer",
      pe: 14.5,
      pb: 3.8,
      roe: 24.0,
      debtToEquity: 1.8,
      dividendYield: 7.5,
      themes: ["Infrastructure Capex", "Semiconductors"],
    },
  },
  {
    ticker: "HINDALCO",
    name: "Hindalco Industries Ltd",
    exchange: "NSE",
    isin: "INE038A01020",
    sector: "Metals & Mining",
    industry: "Aluminium & Copper",
    marketCapCr: 155_000,
    indices: [N50, METAL],
    providerToken: "1363",
    sim: {
      basePrice: 690,
      annualVol: 0.30,
      annualDrift: 0.22,
      avgVolume: 7_800_000,
      scenario: "ema-golden-cross",
      archetype: "cyclical",
      pe: 15.2,
      pb: 1.6,
      roe: 11.0,
      debtToEquity: 0.52,
      dividendYield: 0.5,
      themes: ["EV Charging Infrastructure", "Infrastructure Capex"],
    },
  },
  {
    ticker: "BANKBARODA",
    name: "Bank of Baroda",
    exchange: "NSE",
    isin: "INE028A01039",
    sector: "Financial Services",
    industry: "Public Sector Bank",
    marketCapCr: 130_000,
    indices: [NEXT50, BANK],
    providerToken: "4668",
    sim: {
      basePrice: 250,
      annualVol: 0.32,
      annualDrift: 0.18,
      avgVolume: 19_000_000,
      scenario: "support-bounce",
      archetype: "deep-value",
      pe: 7.2,
      pb: 1.1,
      roe: 17.0,
      debtToEquity: 0.0,
      dividendYield: 3.0,
      themes: ["Financial Inclusion", "Infrastructure Lending"],
    },
  },
  {
    ticker: "PNB",
    name: "Punjab National Bank",
    exchange: "NSE",
    isin: "INE160A01022",
    sector: "Financial Services",
    industry: "Public Sector Bank",
    marketCapCr: 125_000,
    indices: [NEXT50, BANK],
    providerToken: "10666",
    sim: {
      basePrice: 115,
      annualVol: 0.38,
      annualDrift: 0.24,
      avgVolume: 42_000_000,
      scenario: "range-breakout",
      archetype: "deep-value",
      pe: 10.5,
      pb: 1.2,
      roe: 12.5,
      debtToEquity: 0.0,
      dividendYield: 1.3,
      themes: ["Financial Inclusion"],
    },
  },
];

export const BENCHMARK = {
  symbol: "NIFTY 50",
  ticker: "NIFTY50",
  basePrice: 22_400,
  annualVol: 0.13,
  annualDrift: 0.12,
} as const;

export const SEED_BY_TICKER = new Map(SEED_INSTRUMENTS.map((i) => [i.ticker, i]));

/** Distinct structural themes across the universe, for the thematic strategy. */
export const ALL_THEMES = Array.from(
  new Set(SEED_INSTRUMENTS.flatMap((i) => i.sim.themes)),
).sort();
