/**
 * Rewrite the adaptive-icon XML that `capacitor-assets` emits.
 *
 * The generator wraps both layers in `<inset android:inset="16.7%">`. That is
 * the right hedge when a foreground still carries its own tile and padding is
 * the only thing keeping the seams out of the mask — but ours does not. After
 * `generate-icons.ts` the background is a full-bleed gradient and the
 * foreground is the bare mark at 61% of the canvas, which is exactly the safe
 * zone Android guarantees. Insetting on top of that applies the padding twice:
 * the background stops short of the mask edge and the mark lands at ~40% of
 * the icon, which is the "small glyph in a big tile" look this replaces.
 *
 * Run as part of `npm run icons:android`, after the generator, because the
 * generator rewrites these files every time it runs.
 */

import { readdir, writeFile } from "node:fs/promises";
import path from "node:path";

const RES_DIR = path.join(process.cwd(), "android", "app", "src", "main", "res", "mipmap-anydpi-v26");

function xml(variant: string): string {
  return `<?xml version="1.0" encoding="utf-8"?>
<!--
    Adaptive launcher icon${variant}.

    Generated by scripts/adaptive-icon-xml.ts. Do not add an <inset> here: the
    artwork in assets/ already carries the correct geometry, and insetting
    applies that padding a second time. If the mark needs more breathing room,
    change SAFE_ZONE in scripts/generate-icons.ts instead.
-->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
</adaptive-icon>
`;
}

async function main() {
  const files = (await readdir(RES_DIR)).filter((f) => f.endsWith(".xml"));
  if (files.length === 0) {
    throw new Error(`No adaptive-icon XML found in ${RES_DIR}. Run capacitor-assets first.`);
  }

  for (const file of files) {
    const variant = file.includes("round") ? ", round mask variant" : "";
    await writeFile(path.join(RES_DIR, file), xml(variant), "utf8");
    console.log(`  rewrote ${file} without insets`);
  }
}

void main();
